### PR TITLE
Normalise.py changes for MACE use

### PR DESCRIPTION
**Pull request by digitensions**
Ran a 2to3 pass and tested here at MACE. Working great! Added missing parenthesis at line 123, and amendment to slices - now 24. Not sure if you'll want to replace your own with this, so should I change slices back to 16?

Woohoo. Made an IFIscripts pull request though :) thanks for suggesting Kieran.

### CODE REVIEW

**Comment by b00giehead** [comment]
Hang on, had a fail at the end on my MacPro with this code although it works fine on laptop... reviewing

**Comment by b00giehead** [comment]
Ran a 2to3 on ififuncs.py also, and it's working fine now. Want me to add this change to ififuncs.py as a commit too?

**Comment by kieranjol** [comment]
Thank you,I'll hopefully be able to test ASAP.. ififuncs is a bit of a
beast to transition from 2 to 3 as almost every script uses it and there's
so much potential for errors to creep in due to not having an automated
test suite.

Thanks again!

**Comment by kieranjol** [comment]
Hi Joanna, the actual 2to3 stuff looks great and I think that the bump up to 24 slices is a good idea. Maybe I/someone could add an argparse argument to specify the slice count maybe?

Also is there any chance that you were using an older version of normalise.py? I see a bunch of deletions in the diff towards the end of your Pull Request, which make me think that you didn't use the latest version in the master branch?

**Comment by b00giehead** [comment]
Hi Kieran,  It's very possible I thought I'd downloaded the latest version when it was an original. So sorry! Can you send a link to where I download from when you get time?  Just so I can be sure.  Thanks :)

**Comment by kieranjol** [comment]
Heyyy, the download link on the main GitHub page should do the trick...

**Comment by b00giehead** [comment]
Well I'm pretty sure that's where I downloaded it from, twice. I'll try again and compare the code to the Master branch to be sure :)

**Comment by kieranjol** [comment]
Cheers joanna

**Comment by digitensions** [comment]
Hey, well I've managed to resolve the issue on work Mac. Despite replicating the alterations on MACE MacPro, the only way to fix it was to copy the working normalise/ififuncs across to MACE MacPro... No idea why but at least there aren't deeper issues with the Mac's python set up. Should I do anything to check this normalise.py version against your script or do you just want to burnnnn this wasted PR!

**Comment by digitensions** [comment]
Today I discovered I can close things, so shutting this one down and considering it a success. Thanks for help!

**Pull request closed without merging**
