### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by kieranjol**
The goal for now is to support both python 2 and python 3, using the `future` pip package when necessary.
so far it's been things like subprocess.check_output no longer return strings, as well as the expect print() differences.
This should fix https://github.com/kieranjol/IFIscripts/issues/292

### CODE REVIEW

**Comment by mcampos-quinn** [comment]
Party time!

**Comment by b00giehead** [comment]
Thank you for the steer, this is brilliant.

**Comment by kieranjol** [comment]
For the most part it's just simple things like not having brackets for print statements. I might try to fast-track some upgrades this week..My main worry is upgrading python itself on like 12 computers, OSX/linux/Windows..

**Comment by b00giehead** [comment]
Sounds like a good new year job to me :) to use updated copyit on Python3 will I need to update the files referenced at the head also, like ififuncs?  Thanks.

**Comment by kieranjol** [comment]
Hi Joanna:
You probably installed ifiscripts via pip? You might be best off uninstalling those for the moment as they might not work so well with python3.
if you did want to test out this branch, you could do the following:
```
git clone https://github.com/kieranjol/ifiscripts
git checkout python3
./copyit.py path/to/source_dir path/to/destination_dir
```

Lemme know how you get on with that.. the `./` is very important when running the scripts. You might need to do
`python copyit.py` instead, depending on your environment.

Any testing on this branch would be greatly appreciated!

**Comment by b00giehead** [comment]
Is this the best place to feedback? Happy to try and test these for you 👍 

Joannas-MacBook-Pro-2:ifiscripts Joanna$ ./copyit.py /Users/Joanna/Desktop/TestMov /Users/Joanna/Desktop/CopyitMov
Traceback (most recent call last):
  File "./copyit.py", line 15, in <module>
    from builtins import input
ImportError: No module named builtins
Joannas-MacBook-Pro-2:ifiscripts Joanna$ search builtins
-bash: search: command not found
Joannas-MacBook-Pro-2:ifiscripts Joanna$ 

Sorry I can't diagnose. One day!

**Comment by b00giehead** [comment]
Not sure if the log is interesting to you, it has a report of

> 2018-11-20T13:27:55 Joanna copyit.py started. 
> 2018-11-20T13:27:55 Joanna eventDetail=copyit.py Script version unavailable as the ifiscripts repository is not installed in $HOME/ifigit/ifiscripts 

Everything else seemed very successful

**Comment by kieranjol** [comment]
Awesome, you can try to copy a folder too.
I need to sort out that logging too,thanks for sending that on!

**Comment by b00giehead** [comment]
Thanks Kieran, that's awesome. And will do ref folder copying. I take it I can test all ifiscripts the same way via this git install? I'll attempt to install the same tomorrow on work computers and make some proper directory copies.

Have you used copyit with LTO? Or something like?

**Comment by kieranjol** [comment]
yes, you can attempt them all via this method, though i've updated a few scripts since this pull request. 
We used copyit a lot with LTO, but using the -lto argument. This uses gcp, not rsync for the file transfer and it tends to have fewer headaches.
You might need to do
`brew install coreutils` in order to get access to gcp ..

**Comment by b00giehead** [comment]
I have coreutils, but never tried copying with gcp, so I'll have to look into how I'd run that with a python script as well.  I installed a ton of stuff from GNU after hearing Richard Stallman talk at Uni of Lincoln, but never did anything else with it! 

20 mov items copied with copyit perfectly. Thanks so much for all this.

**Comment by kieranjol** [comment]
I think I might just merge this tomorrow. i think all I need to do is install `future` on each active workstation. This should bring most scripts up to date and should be python 2/3 compatible, and I can make tweaks in the master branch as I go. The ultimate goal will be to remove the use of `future` so that python3 will be the only supported version.

**Comment by b00giehead** [comment]
Copied a folder overnight with 13 movs at 210GB, all went well and checksums all matched.  The same method of cd into ifiscripts worked fine here at MACE. Took an awfully long time though, but I definitely have an issue with processing speeds on this Mac at the moment - something for me to investigate!  Thanks very much for this route into IFIscripts Kieran, looking forward to trying some others out in coming weeks/months.  👍

**Comment by kieranjol** [comment]
That's awesome Joanna - how slow was it? what kind of  transfer speeds were you getting with rsync? it's be great if you could post the log that appeared on your desktop..

**Comment by kieranjol** [comment]
I'd consider 33megs a second to be fairly slow,but it probably depends on
your connection to your server and how many simultaneous transfers are
happening. What kind of speeds would you be expecting? Also if you have
preexisting sidecar manifests,you can get a bit of a speed increase as the
initial generating source manifest step is skipped..

**Pull request closed without merging**
