### PR TITLE
adds make_mediaconch.py

### PR DESCRIPTION
**Pull request by kieranjol**
This script runs mediaconch with a policy against all files in subdirectories. It will provide a pass/fail report to the terminal, but it will also generate XML sidecars for each video file that detail the report.
You provide your input directory, your policy, as well as a filename extension. This allows you to do the following: 
* Scenario - Vendor provides a drive with mov/m2t and dv files.
* Run make_mediaconch once with the m2t/HDV policy but also specify with the `-object_extension_pattern` option that you only want it to run the policy against m2t files. This prevents a bunch of false errors when it tries to validate DV and mov with the HDV policy.
* You can run makemediaconch multiple times for the different filetypes and policies.
```
positional arguments:
  input                 path to parent directory

optional arguments:
  -h, --help            show this help message and exit
  -object_extension_pattern OBJECT_EXTENSION_PATTERN
                        the filename extension that you would like to scan for
  -policy POLICY        the full path to the mediaconch XML policy
```

Example usage:
```
make_mediaconch.py E:\DV_batches -p C:\Users\kieran.oleary\Documents\HDV_mediaconch_policy.xml -object_extension_pattern m2t
2020-06-24 08:17:38,076 - MV8805.m2t: No failure detected
2020-06-24 08:17:38,077 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8805\MV8805.m2t_MediaConchReport.xml
2020-06-24 08:17:38,748 - MV8807.m2t: No failure detected
2020-06-24 08:17:38,749 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8807\MV8807.m2t_MediaConchReport.xml
2020-06-24 08:17:39,074 - MV8810.m2t: No failure detected
2020-06-24 08:17:39,074 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8810\MV8810.m2t_MediaConchReport.xml
2020-06-24 08:17:39,401 - MV8811.m2t: No failure detected
2020-06-24 08:17:39,417 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8811\MV8811.m2t_MediaConchReport.xml
2020-06-24 08:17:39,751 - MV8906.m2t: No failure detected
2020-06-24 08:17:39,751 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8906\MV8906.m2t_MediaConchReport.xml
2020-06-24 08:17:40,099 - MV8907.m2t: No failure detected
2020-06-24 08:17:40,100 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8907\MV8907.m2t_MediaConchReport.xml
2020-06-24 08:17:40,426 - MV8908.m2t: No failure detected
2020-06-24 08:17:40,427 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8908\MV8908.m2t_MediaConchReport.xml
2020-06-24 08:17:40,743 - MV8910.m2t: No failure detected
2020-06-24 08:17:40,744 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8910\MV8910.m2t_MediaConchReport.xml
2020-06-24 08:17:41,083 - MV8985.m2t: No failure detected
2020-06-24 08:17:41,084 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8985\MV8985.m2t_MediaConchReport.xml
2020-06-24 08:17:41,412 - MV8986.m2t: No failure detected
2020-06-24 08:17:41,412 - Generating sidecar - E:\DV_batches\IFI_Batch_10\MV8986\MV8986.m2t_MediaConchReport.xml
2020-06-24 08:17:41,750 - MV8782.m2t: No failure detected
2020-06-24 08:17:41,750 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8782.m2t_MediaConchReport.xml
2020-06-24 08:17:42,070 - MV8942.m2t: No failure detected
2020-06-24 08:17:42,071 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8942\MV8942.m2t_MediaConchReport.xml
2020-06-24 08:17:42,394 - MV8943.m2t: No failure detected
2020-06-24 08:17:42,396 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8943\MV8943.m2t_MediaConchReport.xml
2020-06-24 08:17:42,735 - MV8944.m2t: No failure detected
2020-06-24 08:17:42,736 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8944\MV8944.m2t_MediaConchReport.xml
2020-06-24 08:17:43,058 - MV8945.m2t: No failure detected
2020-06-24 08:17:43,059 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8945\MV8945.m2t_MediaConchReport.xml
2020-06-24 08:17:43,390 - MV8947.m2t: No failure detected
2020-06-24 08:17:43,391 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8947\MV8947.m2t_MediaConchReport.xml
2020-06-24 08:17:43,728 - MV8948.m2t: No failure detected
2020-06-24 08:17:43,729 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8948\MV8948.m2t_MediaConchReport.xml
2020-06-24 08:17:44,049 - MV8949.m2t: No failure detected
2020-06-24 08:17:44,053 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8949\MV8949.m2t_MediaConchReport.xml
2020-06-24 08:17:44,397 - MV8955.m2t: No failure detected
2020-06-24 08:17:44,398 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8955\MV8955.m2t_MediaConchReport.xml
2020-06-24 08:17:44,728 - MV8956.m2t: No failure detected
2020-06-24 08:17:44,728 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8956\MV8956.m2t_MediaConchReport.xml
2020-06-24 08:17:45,054 - MV8957.m2t: No failure detected
2020-06-24 08:17:45,054 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8957\MV8957.m2t_MediaConchReport.xml
2020-06-24 08:17:45,387 - MV8971.m2t: No failure detected
2020-06-24 08:17:45,387 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV8971\MV8971.m2t_MediaConchReport.xml
2020-06-24 08:17:45,719 - MV9101.m2t: No failure detected
2020-06-24 08:17:45,720 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV9101\MV9101.m2t_MediaConchReport.xml
2020-06-24 08:17:46,036 - MV9109.m2t: No failure detected
2020-06-24 08:17:46,046 - Generating sidecar - E:\DV_batches\IFI_Batch_11\MV9109\MV9109.m2t_MediaConchReport.xml
2020-06-24 08:17:46,384 - MV8782.m2t: No failure detected
2020-06-24 08:17:46,385 - Generating sidecar - E:\DV_batches\IFI_New_Versions_June20\MV8782_V2\MV8782.m2t_MediaConchReport.xml
2020-06-24 08:17:46,757 - MV9025.m2t: No failure detected
2020-06-24 08:17:46,757 - Generating sidecar - E:\DV_batches\IFI_New_Versions_June20\MV9025\MV9025.m2t_MediaConchReport.xml
```

### CODE REVIEW

**Comment by raecasey** [comment]
could i test this out before it merges? I have an example I can work with here. maybe you could give me instructions on how to access the branch to test it (it's been a while since i've done that). just to warn you though that it will be tomorrow before i get a chance to test it out.

**Comment by kieranjol** [comment]
Hi raelene, absolutely - assuming you're using mov files:
```
update.py
cd
cd ifigit
cd ifiscripts
git checkout makemediaconch
python3 make_mediaconch.py path/to/videos -p path/to/policy.xml -object_extension_pattern mov 
```
if the command doesn't run, maybe run `python make_mediaconch.py path/to/videos -p path/to/policy.xml -object_extension_pattern mov ` instead (removing python3 and just saying python - this might be necessary if running on windows)

**Comment by raecasey** [comment]
i'll be using mkv files. and have that policy here with me. and change the -object_extension_pattern to mkv
is that right?

**Comment by kieranjol** [comment]
Perfecto!

**Comment by raecasey** [comment]
the command ran but then failed. see below:


C:\Users\yhuang>cd
C:\Users\yhuang

C:\Users\yhuang>cd ifigit

C:\Users\yhuang\ifigit>cd ifiscripts

C:\Users\yhuang\ifigit\ifiscripts>git checkout makemediaconch
Switched to a new branch 'makemediaconch'
Branch 'makemediaconch' set up to track remote branch 'makemediaconch' from 'origin'.

C:\Users\yhuang\ifigit\ifiscripts>python3 make_mediaconch.py D:\ballymun\dsm\Batch_5_Redone\MKV -p "C:\Users\yhuang\Desktop\joefixity_report\Specialist AV PAL MKV_mediaconch_policy.xml" -object_extension_pattern mkv

C:\Users\yhuang\ifigit\ifiscripts>python make_mediaconch.py D:\ballymun\dsm\Batch_5_Redone\MKV -p "C:\Users\yhuang\Desktop\joefixity_report\Specialist AV PAL MKV_mediaconch_policy.xml" -object_extension_pattern mkv
Traceback (most recent call last):
  File "make_mediaconch.py", line 58, in <module>
    main()
  File "make_mediaconch.py", line 44, in main
    mediaconch_output = subprocess.check_output(mediaconch_cmd)
  File "C:\Users\yhuang\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\yhuang\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\yhuang\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\yhuang\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kieranjol** [comment]
Hi Raelene - looks like you don't have mediaconch command line tool installed? 
I added some code to pick up on missing external dependencies like this, but it appears that on your instance, a custom WinError appeared which i hadn't factored in.
You'll need to pick this up from here: https://mediaarea.net/download/snapshots/binary/mediaconch/20200624/ - looks like you're on windows so it's the last link there for windows x64 that you'll need
You'll need to place the mediaconch exe inside of that zip into a location where the scripts can find it - maybe while testing you can just put it in to ifigit/ifiscripts?

K

**Comment by raecasey** [comment]
works! brilliant. 
a few questions:
is this something that can be done when offline? 
will future updates of the mediaconch app effect this script?
what about the implementation report?

**Comment by kieranjol** [comment]
> works! brilliant.

yayyy
> a few questions:
> is this something that can be done when offline?
Absolutely - it's an offline process
> will future updates of the mediaconch app effect this script?
hmmm probably not - mediaconch would have to change in a gigantic fashion for this to happen 
> what about the implementation report?
It should be next to your video file as a sidecar? the script should report it's exact location like

2020-06-24 08:17:46,757 - Generating sidecar - E:\DV_batches\IFI_New_Versions_June20\MV9025\MV9025.m2t_MediaConchReport.xml

**Comment by kieranjol** [comment]
Arg - dang - you mean the FFV1/MKV validation? I hadn't factored that in actually cos I'm not dealing with those formats at the moment. I can also add in a validation if the filetype.endswith(mkv)?

**Comment by kieranjol** [comment]
Thanks for all that - so yeah, i'll look into adding the mkv check so it can do the implementation report for mkv - merci!

**Comment by kieranjol** [comment]
Hi @raecasey  - I added the implementationReport support. Here's the output:
```
>make_mediaconch.py E:\test -object_extension_pattern mkv  -p C:\Users\kieran.oleary\Documents\HDV_mediaconch_policy.xml
2020-06-26 09:08:06,626 - G1.mkv does not validate against the policy - look at the sidecar XML for more info
2020-06-26 09:08:06,627 - Generating sidecar - E:\test\G1\G1.mkv_MediaConchReport.xml
2020-06-26 09:08:07,070 - G1.mkv: Valid implementation
2020-06-26 09:08:07,150 - Generating implementation report sidecar: E:\test\G1\G1.mkvImplementationReport.xml
```
to test it out - it's similar to before but with an extra `git pull`

```
update.py
cd
cd ifigit
cd ifiscripts
git checkout makemediaconch
git pull
python3 make_mediaconch.py path/to/videos -p path/to/policy.xml -object_extension_pattern mkv 
```

The extra code I wrote is super inefficient but it does the job - and it's low hanging fruit for Colm or Noelia to refactor into functions when they get more comfortable.

**Comment by bturkus** [comment]
Kieran & Co.: have you thought at all about ways to automate the testing of a large group of mixed media files against multiple policies? So, for example, we’ll regularly receive hard drives with 1,200 audio files, some derived from analog tape but others from various digital audio formats. Currently we run different policies over the same group and cross-check the results, but we’ve envisioned (though never committed the time to) coming up with a way to run one script that would spit out something like: 1,200 files counted, 1,000 pass policy A, 199 pass policy B, 1 failed both policies for these reasons.

**Comment by kieranjol** [comment]
Hiya Ben - I appreciate you checking in so much!
I think that this is actually super simple to implement, it would just involve:
* provide multiple policies
* have counters running in the script to tally things up
* have decision trees set up so if fail; then try other policy, if two fails; report at end

All this would have been easier to add to our script if I hadn't baked in a bunch of technical debt by being lazy - but off the top of my head this would be doable with about an hours work.

**Comment by kieranjol** [comment]
Also this also makes me realise that I should have a final report at the end of the current script regardless..

**Pull request merged**
