### PR TITLE
add copy of pymmconfig

### PR DESCRIPTION
**Pull request by mcampos-quinn**
Hi Kieran,

Here's a copy of pymmconfig! I hope it's helpful! Just looking through it there's a lot of junk I had forgotten about. I pasted in a couple of functions that are used from the `pymmFunctions` file so you don't need it, but commented out the original references that you can delete. 

The interview logic is a little rickety, so I hope you can get what you need!

Thanks!
Michael

### CODE REVIEW

**Comment by mcampos-quinn** [comment]
It looks like this wants to merge to your master branch... I had made a separate branch, but sorry, I don't know how to direct the PR to a branch other than master... :/

**Comment by kieranjol** [comment]
Ahhh,these additions are so thoughtful. I took a quick look at some of your comments as well. I am going to just merge to master tomorrow and make some quick edits.thank you!
.

**Comment by kieranjol** [comment]
Sorry for the delay, a million thanks @mcampos-quinn !!

**Comment by mcampos-quinn** [comment]
Whee!

**Pull request merged**
