### PR TITLE
Copyit

### PR DESCRIPTION
**Pull request by kieranjol**
This still needs some work but posting it as a pull request for more visibility.
Key changes so far are:
* Complete rewrite of `moveit.py` to make it more of a microservice that can link up with other scripts
* Rename `moveit.py` to `copyit.py`
* `copyit.py` can now copy single files. 
* Uses more PREMIS language in logs
* Start and end of events are logged sepereately now, as per this doc http://www.loc.gov/standards/premis/v3/preservation-events.pdf
* Functions added so that version info can be extracted from scripts: SHA:ISO8601 date
* log filenames can be returned as a value from `copyit.main()`, allow for a better microservice pipeline

Example new log style - using `sipcreator.py` which launches `copyit.py` instances
```

2017-07-04T15:32:20 Digital Garage EVENT = sipcreator.py started 
2017-07-04T15:32:20 Digital Garage eventDetail=sipcreator.py f5245c063ccd9f64d235cc215b4ea8604e140e32:2017-07-04T13:02:16+01:00 
2017-07-04T15:32:20 Digital Garage EVENT = agentName=Kieran O'Leary 
2017-07-04T15:32:20 Digital Garage EVENT = eventType=Identifier assignement, eventIdentifierType=UUID, value=185b1cbe-d168-4b6d-b018-b1695baf1b29, module=uuid.uuid4 
2017-07-04T15:32:20 Digital Garage copyit.py started. 
2017-07-04T15:32:20 Digital Garage eventDetail=copyit.py 95bcd1773c89a278f35b1592475d3ec4c7405a56:2017-07-04T01:00:16+01:00 
2017-07-04T15:32:20 Digital Garage Source: C:\Users\Digital Garage\output5.mov 
2017-07-04T15:32:20 Digital Garage Destination: C:\Users\Digital Garage\Documents\185b1cbe-d168-4b6d-b018-b1695baf1b29\objects 
2017-07-04T15:32:20 Digital Garage EVENT = Generating source manifest: status=started, eventType=message digest calculation, module=hashlib 
2017-07-04T15:32:33 Digital Garage EVENT = Generating source manifest: status=completed 
2017-07-04T15:32:33 Digital Garage EVENT = File Transfer, status=started, agentName=Windows, module=shutil.copy2 
2017-07-04T15:32:42 Digital Garage EVENT = File Transfer, status=completed 
2017-07-04T15:32:42 Digital Garage EVENT = Generating destination manifest: status=started, eventType=message digest calculation, module=hashlib 
2017-07-04T15:32:56 Digital Garage EVENT = Generating destination manifest: status=completed 
2017-07-04T15:32:56 Digital Garage EVENT = File Transfer Judgement - Success, eventOutcome=pass 

```

To be done: Add warning to windows single file copy as windows folder copy via `robocopy` will preserve all dates, but `Robocopy` does not support single file copy, and any windows tool that does this will not preserve `Date Created`.

### CODE REVIEW

**Comment by kieranjol** [comment]
Latest log file - metadata extraction event added:

**Comment by kieranjol** [comment]
And the actual log this time:
```

2017-07-04T16:31:01 Digital Garage EVENT = sipcreator.py started 
2017-07-04T16:31:01 Digital Garage eventDetail=sipcreator.py 69fe2d5c379ea2d8481d316ac6e855582f972d09:2017-07-04T15:34:31+01:00 
2017-07-04T16:31:01 Digital Garage EVENT = agentName=Kieran O'Leary 
2017-07-04T16:31:01 Digital Garage EVENT = eventType=Identifier assignement, eventIdentifierType=UUID, value=9db8e3cc-dd0a-46ae-a51c-d8e91320b789, module=uuid.uuid4 
2017-07-04T16:31:01 Digital Garage copyit.py started. 
2017-07-04T16:31:02 Digital Garage eventDetail=copyit.py 69fe2d5c379ea2d8481d316ac6e855582f972d09:2017-07-04T15:34:31+01:00 
2017-07-04T16:31:02 Digital Garage Source: C:\Users\Digital Garage\output5.mov 
2017-07-04T16:31:02 Digital Garage Destination: C:\Users\Digital Garage\Documents\9db8e3cc-dd0a-46ae-a51c-d8e91320b789\objects 
2017-07-04T16:31:02 Digital Garage EVENT = Generating source manifest: status=started, eventType=message digest calculation, module=hashlib 
2017-07-04T16:31:15 Digital Garage EVENT = Generating source manifest: status=completed 
2017-07-04T16:31:15 Digital Garage EVENT = File Transfer, status=started, agentName=Windows, module=shutil.copy2 
2017-07-04T16:31:25 Digital Garage EVENT = File Transfer, status=completed 
2017-07-04T16:31:25 Digital Garage EVENT = Generating destination manifest: status=started, eventType=message digest calculation, module=hashlib 
2017-07-04T16:31:39 Digital Garage EVENT = Generating destination manifest: status=completed 
2017-07-04T16:31:39 Digital Garage EVENT = File Transfer Judgement - Success, eventOutcome=pass 
2017-07-04T16:31:40 Digital Garage EVENT = Metadata extraction - eventDetail=Technical metadata extraction via mediainfo, eventOutcome=C:\Users\Digital Garage\Documents\9db8e3cc-dd0a-46ae-a51c-d8e91320b789\metadata/output5.mov_mediainfo.xml, agentName=MediaInfoLib - v0.7.72 
2017-07-04T16:31:40 Digital Garage EVENT = Metadata extraction - eventDetail=Mediatrace technical metadata extraction via mediainfo, eventOutcome=C:\Users\Digital Garage\Documents\9db8e3cc-dd0a-46ae-a51c-d8e91320b789\metadata/output5.mov_mediainfo.xml, agentName=MediaInfoLib - v0.7.72 

```

**Comment by raecasey** [comment]
looks really great Kieran.
would like to thrash out the benefit of having such specific premis language in the log files. if it will be easy to sustain and maintain etc. we can do that at the dcm
also, a few other questions about the manifest versioning and also what you mean in the last bullet point about log filenames.
but apart from those questions, - it's brilliant. thanks for this.
talk tomo

**Comment by kieranjol** [comment]
Hey, thanks! 

Yes, let's discuss it further. I'm not 100% on the usage of PREMIS terms either, but the thinking is that because of the (hopefully) consistent use of delimiters (premisSemanticUnit=value), it would be a lot easier to transform those logs into a more formal PREMIS document like XML. And regardless of the laguage used, the logs now just record some extra info that they weren't recording before.

I'm thinking of instead of just having EVENT for everything, some of them could be called PREMISEVENT - to signify that these are actual PREMIS events, while others are more like system events that we can record in the logs but not with PREMIS. It would make it a lot easier for a script to transform the logs to XMl. however..

Also, i'm leaning more towards having two running logs: One textfile log like the example above, but also a PREMIS CSV like this - https://docs.google.com/spreadsheets/d/1FeErFW-J-bNreC-UPK3X1oqpW3s3HL4nwZ3EZUVt6sE/edit?usp=sharing which should allow for a very easy transform to XML/human readable text/json/whatever. there would be some repetition but I think both could be very useful and I think they could both work well together. let's discuss that more anyhow.

As for the last bullet point, it's more of a backend change but it is one of the first examples where the scripts can talk to each other and return values along a kind of pipeline. If you take masscopy.py, it was really just launching loads of moveit.py seperate instances, which made individual logs in the desktop. When masscopy would finish running, it had to look through the logs directory , guess the filenames (As the log files have the date and time at the end of the filename, it would do it's best to guess, but it would be out by a second some times and the script would have to adjust - see here for the mess: https://github.com/kieranjol/IFIscripts/blob/master/masscopy.py#L85) , and then try to determine if the moveit.py was a success or failure. This was because moveit.py would just run as a totally seperate service, and it couldn't pass values back to masscopy - like the name of the logs or if things were a success of failure. Now, because the code has been altered, if moveit (or copyit) runs as part of another script, moveit can tell the parent script if things were a success or failure or whatever else. Eventually, if all the scripts start doing this, it just makes them so much more flexible.

Btw, here's the specific line in sipcreator - https://github.com/kieranjol/IFIscripts/pull/185/files#diff-62d63be3c9579bd67d0d942f743e6a6bR92
` log_name = copyit.main([item, os.path.join(sip_path, 'objects')])`

copyit is running there as a function, `item` being source, `os.path.join(sip_path, 'objects')` is the destination (literally sip_path/objects) but that process is returning a value which is stored as log_name.
After talking this through, I know realise that returning the log name from the script and then looking through the logs to see if it was a success is totally redundant. All that needs to be returned is a simple PASS/FAIL and that's all. much more accurate and less work.

**Comment by kieranjol** [comment]
aaaaand here;s what the latest log file looks like when  `concat.py -s` runs, as it
* concats source files into a concatted mkv
* runs `sipcreator` to make a SIP
* which in turn runs `copyit.py` instances

but all processes are documented in the one log file which looks like this:
```
2017-07-05T23:51:58 kieranjol concat.py started. 
2017-07-05T23:51:58 kieranjol eventDetail=concat.py a351cd9f277d2ca3f3017f15d5d80a04ed9a8ea3:2017-07-05T22:49:05+01:00 
2017-07-05T23:52:00 kieranjol EVENT = agentName=Kieran O'Leary 
2017-07-05T23:52:03 kieranjol Relationship, derivation, has source=49a682e2-567d-417d-851c-8023412623a8 
2017-07-05T23:52:03 kieranjol EVENT = sipcreator.py started 
2017-07-05T23:52:03 kieranjol eventDetail=sipcreator.py a351cd9f277d2ca3f3017f15d5d80a04ed9a8ea3:2017-07-05T22:49:05+01:00 
2017-07-05T23:52:03 kieranjol EVENT = agentName=Kieran O'Leary 
2017-07-05T23:52:03 kieranjol EVENT = eventType=Identifier assignement, eventIdentifierType=UUID, value=ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0, module=uuid.uuid4 
2017-07-05T23:52:03 kieranjol copyit.py started. 
2017-07-05T23:52:03 kieranjol eventDetail=copyit.py 2a858c228c8c2b767abde20936d251f81a2d5e3c:2017-07-04T16:47:07+01:00 
2017-07-05T23:52:03 kieranjol Source: /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0.mkv 
2017-07-05T23:52:03 kieranjol Destination: /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/objects 
2017-07-05T23:52:03 kieranjol EVENT = Generating source manifest: status=started, eventType=message digest calculation, module=hashlib 
2017-07-05T23:52:03 kieranjol EVENT = Generating source manifest: status=completed 
2017-07-05T23:52:03 kieranjol EVENT = File Transfer, status=started, agentName=Linux, agentName=cp 
2017-07-05T23:52:03 kieranjol EVENT = File Transfer, status=completed 
2017-07-05T23:52:03 kieranjol EVENT = Generating destination manifest: status=started, eventType=message digest calculation, module=hashlib 
2017-07-05T23:52:03 kieranjol EVENT = Generating destination manifest: status=completed 
2017-07-05T23:52:03 kieranjol EVENT = File Transfer Judgement - Success, eventOutcome=pass 
2017-07-05T23:52:03 kieranjol EVENT = Metadata extraction - eventDetail=Technical metadata extraction via mediainfo, eventOutcome=/home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/metadata/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0.mkv_mediainfo.xml, agentName=mediainfo 
2017-07-05T23:52:03 kieranjol EVENT = Metadata extraction - eventDetail=Mediatrace technical metadata extraction via mediainfo, eventOutcome=/home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/metadata/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0.mkv_mediainfo.xml, agentName=mediainfo 
2017-07-05T23:52:03 kieranjol EVENT = Manifest consolidation - Checksums from /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/objects/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0.mkv_manifest.md5 merged into /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0_manifest.md5 
2017-07-05T23:52:03 kieranjol EVENT = Manifest movement - Manifest from /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/objects/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0.mkv_manifest.md5 to /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/logs 
2017-07-05T23:52:03 kieranjol EVENT = Manifest consolidation - Checksums from /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/metadata/metadata_manifest.md5 merged into /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0_manifest.md5 
2017-07-05T23:52:03 kieranjol EVENT = Manifest movement - Manifest from /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/metadata/metadata_manifest.md5 to /home/kieranjol/Downloads/CHARBON-SMPTE-24/ca2c05bd-07f1-44c8-b72a-0a15bdabf4a0/logs 
```

**Comment by kieranjol** [comment]
`validate.py` fixity checks will now update the sip/aip logfile, but the checksum for the logfile will have to be updated in the manifest, also for the concat log merge.
Also, `validate.py` uses the `logging` module, which is better practise than our `generate_log` functions, but for consistencies sake, I think we should commit to `generate_log`.

**Pull request merged**
