### PR TITLE
Tape Ingest host computers

### PR DESCRIPTION
**Pull request by ecodonohoe**
Have added serial numbers

### CODE REVIEW

**Comment by kieranjol** [comment]
This makes me very happy. Looks great!

**Comment by kieranjol** [comment]
Hi @ecodonohoe ,I can't merge from here
 Looks like you're using an older fork thats about 20 commits behind. I'm assuming you're altering in the browser, so can you delete your fork,refork the latest IFI scripts, and make the changes and send a new pull request?
Also thanks for spotting the Hewlett Packard 2 error. You are correct, that should be removed.
My internet is patchy so reply here or send a Twitter message.

**Comment by ecodonohoe** [comment]
Cool, I thought I was making a bit of a balls of it. Couldn't find where to
delete fork. Will check again later.

Eoin

**Comment by kieranjol** [comment]
Cool, I think you'll have to delete the ifi scripts repository. In the
github desktop app or command line you should be able to update your fork
before making your alterations, not sure how to do it on the site.

**Pull request closed without merging**
