### PR TITLE
brings up to python3

### PR DESCRIPTION
**Pull request by ablwr**
Was just reading about the differences this morning and thought it'd be nice to make these compatible with both versions!

### CODE REVIEW

**Comment by kieranjol** [comment]
Thank you so much,this made my morning! All LGTM at a glance,I'll give it a quick test prior to merging. I knew about the `print` differences,but are quotes also a thing for python3? I have very little consistency in terms of choosing to use single or double quotes :|

**Comment by ablwr** [comment]
Noooo, that was me just picking ty Rome you seeemed to use more and keep it consistent across the script!

**Comment by ablwr** [comment]
Wow, I wrote that quickly on my phone, sorry, I am editing the typos 😆

**Comment by kieranjol** [comment]
Ah yes, I tend to go for single quotes but I never thought about it too much. I genuinely appreciate you checking and matching the style :)

**Comment by kieranjol** [comment]
I just tested `dvsip.py` and all looks well in python 2.7 anyhow. Thank you so much!!!!

**Pull request merged**
