### PR TITLE
Special collections sip

### PR DESCRIPTION
**Pull request by kieranjol**

### CODE REVIEW

**Comment by kieranjol** [comment]
This allows `sipcreator` to be used with documents and images. It uses exiftool to extract metadata, and siegfriend to perform file format identification. It also alters the Object Entry interview in order to accept, but not validate SCOEXXXX numbers.

**Comment by kieranjol** [comment]
Prior to merging - move a lot of code out to a microservice script or to a function in ififuncs.

**Comment by kieranjol** [comment]
Merging - @aoifefitz2016 , I've tested this out and it looks like behaviour has not changed for moving image, this just adds special collections support. However, keep an eye out for any quirks or issues in your first few attempts with this!

**Comment by aoifefitz2016** [comment]
Great, thanks @kieranjol ! Will do.

**Pull request merged**
